
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.9.1
 * Query Engine version: e922089b7d7502aff4249d5da3420f6fa55fc6ad
 */
Prisma.prismaVersion = {
  client: "7.9.1",
  engine: "e922089b7d7502aff4249d5da3420f6fa55fc6ad"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  displayName: 'displayName',
  accountType: 'accountType',
  displayImage: 'displayImage',
  status: 'status',
  isVerified: 'isVerified',
  details: 'details',
  createdAt: 'createdAt',
  linkedAccountId: 'linkedAccountId'
};

exports.Prisma.LinkedAccountScalarFieldEnum = {
  id: 'id',
  platform: 'platform',
  createdOn: 'createdOn',
  connectedBy: 'connectedBy',
  ownerId: 'ownerId',
  moreDetails: 'moreDetails',
  tokenData: 'tokenData'
};

exports.Prisma.ResourceScalarFieldEnum = {
  id: 'id',
  type: 'type',
  accountId: 'accountId',
  uploadedBy: 'uploadedBy',
  value: 'value',
  details: 'details',
  uploadedOn: 'uploadedOn'
};

exports.Prisma.AccountTypeIndividualScalarFieldEnum = {
  accountId: 'accountId',
  firstName: 'firstName',
  middleName: 'middleName',
  lastName: 'lastName',
  dateOfBirth: 'dateOfBirth',
  countryOfResidence: 'countryOfResidence',
  details: 'details',
  roleId: 'roleId'
};

exports.Prisma.AccountTypeBrandScalarFieldEnum = {
  accountId: 'accountId',
  brandName: 'brandName',
  isLegalEntity: 'isLegalEntity',
  originCountry: 'originCountry',
  details: 'details'
};

exports.Prisma.SystemConfigScalarFieldEnum = {
  key: 'key',
  data: 'data',
  updatedAt: 'updatedAt'
};

exports.Prisma.AuthnRequestScalarFieldEnum = {
  id: 'id',
  type: 'type',
  status: 'status',
  data: 'data',
  accountId: 'accountId',
  createdAt: 'createdAt',
  expiresAt: 'expiresAt'
};

exports.Prisma.ActivityScalarFieldEnum = {
  id: 'id',
  memberId: 'memberId',
  actorAccountId: 'actorAccountId',
  action: 'action',
  status: 'status',
  ip: 'ip',
  timestamp: 'timestamp',
  geolocation: 'geolocation'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  applicationId: 'applicationId',
  action: 'action',
  title: 'title',
  message: 'message',
  type: 'type',
  read: 'read',
  createdAt: 'createdAt',
  deletableOn: 'deletableOn',
  persistence: 'persistence',
  detail: 'detail'
};

exports.Prisma.RequestScalarFieldEnum = {
  id: 'id',
  senderId: 'senderId',
  recipientId: 'recipientId',
  status: 'status',
  action: 'action',
  type: 'type',
  data: 'data',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FamilyScalarFieldEnum = {
  id: 'id',
  createdBy: 'createdBy',
  createdAt: 'createdAt'
};

exports.Prisma.FamilyMemberScalarFieldEnum = {
  id: 'id',
  familyId: 'familyId',
  memberId: 'memberId',
  role: 'role'
};

exports.Prisma.VerificationScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  status: 'status',
  reason: 'reason',
  category: 'category',
  doneBy: 'doneBy',
  doneAt: 'doneAt',
  previously: 'previously',
  createdAt: 'createdAt'
};

exports.Prisma.ContactScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  contactType: 'contactType',
  value: 'value'
};

exports.Prisma.NeupIdScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  neupId: 'neupId',
  isPrimary: 'isPrimary',
  dateAdded: 'dateAdded'
};

exports.Prisma.AuthnMethodScalarFieldEnum = {
  accountId: 'accountId',
  value: 'value',
  id: 'id',
  type: 'type',
  order: 'order',
  status: 'status',
  detail: 'detail'
};

exports.Prisma.AuthnSessionScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  key: 'key',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  validTill: 'validTill',
  lastLoggedIn: 'lastLoggedIn',
  loginType: 'loginType',
  geolocation: 'geolocation',
  deviceType: 'deviceType'
};

exports.Prisma.SystemErrorScalarFieldEnum = {
  id: 'id',
  message: 'message',
  context: 'context',
  timestamp: 'timestamp',
  accountId: 'accountId',
  geolocation: 'geolocation',
  ipAddress: 'ipAddress'
};

exports.Prisma.ApplicationProviderScalarFieldEnum = {
  id: 'id',
  providerName: 'providerName',
  providerSite: 'providerSite',
  secretHash: 'secretHash'
};

exports.Prisma.ApplicationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  icon: 'icon',
  website: 'website',
  appSecret: 'appSecret',
  createdAt: 'createdAt',
  endpoints: 'endpoints',
  status: 'status',
  isInternal: 'isInternal',
  responseFields: 'responseFields',
  tokenFields: 'tokenFields',
  details: 'details',
  party: 'party',
  providerId: 'providerId',
  defaultRoleId: 'defaultRoleId'
};

exports.Prisma.ApplicationDevLogScalarFieldEnum = {
  id: 'id',
  appId: 'appId',
  endpoint: 'endpoint',
  method: 'method',
  statusCode: 'statusCode',
  requesterIp: 'requesterIp',
  origin: 'origin',
  referer: 'referer',
  userAgent: 'userAgent',
  requestBody: 'requestBody',
  query: 'query',
  requestMeta: 'requestMeta',
  responseBody: 'responseBody',
  error: 'error',
  createdAt: 'createdAt'
};

exports.Prisma.AssetScalarFieldEnum = {
  id: 'id',
  access_type: 'access_type',
  member_account_id: 'member_account_id',
  member_connection_id: 'member_connection_id',
  access_application_id: 'access_application_id',
  parent_account_id: 'parent_account_id',
  isTemporary: 'isTemporary',
  status: 'status',
  details: 'details'
};

exports.Prisma.MemberScalarFieldEnum = {
  id: 'id',
  memberType: 'memberType',
  memberAccountId: 'memberAccountId',
  parentAccountId: 'parentAccountId',
  status: 'status',
  isTemporary: 'isTemporary',
  details: 'details'
};

exports.Prisma.AccessScalarFieldEnum = {
  id: 'id',
  accessType: 'accessType',
  memberId: 'memberId',
  memberAccountId: 'memberAccountId',
  parentAccountId: 'parentAccountId',
  assetId: 'assetId',
  assetAccountId: 'assetAccountId',
  assetConnectionId: 'assetConnectionId',
  assetApplicationId: 'assetApplicationId',
  accessApplicationId: 'accessApplicationId',
  isTemporary: 'isTemporary',
  roleId: 'roleId',
  status: 'status',
  details: 'details'
};

exports.Prisma.AccountOwnershipScalarFieldEnum = {
  id: 'id',
  parentId: 'parentId',
  childrenId: 'childrenId',
  type: 'type',
  createdAt: 'createdAt'
};

exports.Prisma.ConnectionScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  appId: 'appId',
  roleId: 'roleId',
  status: 'status',
  connectedAt: 'connectedAt',
  details: 'details'
};

exports.Prisma.ApplicationBridgeScalarFieldEnum = {
  id: 'id',
  appId: 'appId',
  type: 'type',
  value: 'value',
  details: 'details',
  createdAt: 'createdAt'
};

exports.Prisma.ApplicationPolicyScalarFieldEnum = {
  id: 'id',
  appId: 'appId',
  policyType: 'policyType',
  policyValue: 'policyValue',
  createdAt: 'createdAt'
};

exports.Prisma.RoleScalarFieldEnum = {
  id: 'id',
  memberId: 'memberId',
  accountId: 'accountId',
  connectionId: 'connectionId',
  assetId: 'assetId',
  assetType: 'assetType',
  assetIdDenorm: 'assetIdDenorm',
  roleId: 'roleId',
  roleName: 'roleName',
  permissions: 'permissions',
  status: 'status',
  details: 'details'
};

exports.Prisma.AuthzPermissionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  appId: 'appId',
  scopeFor: 'scopeFor',
  scopeLevel: 'scopeLevel',
  approvalPolicy: 'approvalPolicy',
  rules: 'rules',
  status: 'status',
  tag: 'tag'
};

exports.Prisma.AuthzRoleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  appId: 'appId',
  scopeFor: 'scopeFor',
  scopeLevel: 'scopeLevel',
  acquisitionType: 'acquisitionType',
  approvalPolicy: 'approvalPolicy',
  pushed: 'pushed',
  applicableFor: 'applicableFor',
  permissions: 'permissions'
};

exports.Prisma.AuthzRolePermissionMapScalarFieldEnum = {
  id: 'id',
  roleId: 'roleId',
  permissionId: 'permissionId',
  scopeFor: 'scopeFor',
  scopeLevel: 'scopeLevel',
  createdAt: 'createdAt'
};

exports.Prisma.AuthzAssetsAccessGrantScalarFieldEnum = {
  id: 'id',
  asset_id: 'asset_id',
  account_id: 'account_id',
  role_id: 'role_id',
  app_id: 'app_id',
  asset_type: 'asset_type'
};

exports.Prisma.PermitScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  memberId: 'memberId',
  forSelf: 'forSelf',
  isRoot: 'isRoot',
  permissions: 'permissions',
  restrictions: 'restrictions',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.IdentityScalarFieldEnum = {
  id: 'id',
  trackId: 'trackId',
  appId: 'appId',
  originatedOn: 'originatedOn',
  refreshesOn: 'refreshesOn',
  validTill: 'validTill',
  details: 'details'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.AssetType = exports.$Enums.AssetType = {
  acc_in_acc: 'acc_in_acc',
  app_in_acc: 'app_in_acc',
  conn_in_acc: 'conn_in_acc'
};

exports.AccessType = exports.$Enums.AccessType = {
  acc_self: 'acc_self',
  acc_self_root: 'acc_self_root',
  acc_in_acc: 'acc_in_acc',
  app_in_acc: 'app_in_acc',
  conn_in_acc: 'conn_in_acc'
};

exports.Prisma.ModelName = {
  Account: 'Account',
  LinkedAccount: 'LinkedAccount',
  Resource: 'Resource',
  AccountTypeIndividual: 'AccountTypeIndividual',
  AccountTypeBrand: 'AccountTypeBrand',
  SystemConfig: 'SystemConfig',
  AuthnRequest: 'AuthnRequest',
  Activity: 'Activity',
  Notification: 'Notification',
  Request: 'Request',
  Family: 'Family',
  FamilyMember: 'FamilyMember',
  Verification: 'Verification',
  Contact: 'Contact',
  NeupId: 'NeupId',
  AuthnMethod: 'AuthnMethod',
  AuthnSession: 'AuthnSession',
  SystemError: 'SystemError',
  ApplicationProvider: 'ApplicationProvider',
  Application: 'Application',
  ApplicationDevLog: 'ApplicationDevLog',
  Asset: 'Asset',
  Member: 'Member',
  Access: 'Access',
  AccountOwnership: 'AccountOwnership',
  Connection: 'Connection',
  ApplicationBridge: 'ApplicationBridge',
  ApplicationPolicy: 'ApplicationPolicy',
  Role: 'Role',
  AuthzPermission: 'AuthzPermission',
  AuthzRole: 'AuthzRole',
  AuthzRolePermissionMap: 'AuthzRolePermissionMap',
  AuthzAssetsAccessGrant: 'AuthzAssetsAccessGrant',
  Permit: 'Permit',
  Identity: 'Identity'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
